{
  description = "Nix Local Cache - A local build service and cache for Nix";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    
    # For building Rust (highly recommended over raw rustPlatform for workspaces)
    crane = {
      url = "github:ipetkov/crane";
    };
    
    # Rust toolchain overlay (needed for crane sometimes, or just good practice)
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, flake-utils, crane, rust-overlay, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs {
          inherit system;
          overlays = [ (import rust-overlay) ];
        };

        # --- Rust Backend Build (using crane) ---
        craneLib = crane.mkLib pkgs;
        
        # Common arguments for all crate builds
        commonArgs = {
          src = pkgs.lib.cleanSourceWith {
            src = craneLib.path ./.;
            filter = path: type:
              (craneLib.filterCargoSources path type) || (builtins.match ".*/migrations/.*" path != null) || (builtins.match ".*/\\.sqlx.*" path != null);
          };
          strictDeps = true;
          
          # Explicitly set package metadata for crane
          pname = "nix-local-cache";
          version = "0.1.0";
          
          buildInputs = [
            pkgs.openssl
            pkgs.pkg-config
            pkgs.sqlite
          ] ++ pkgs.lib.optionals pkgs.stdenv.isDarwin [
            pkgs.libiconv
            pkgs.darwin.apple_sdk.frameworks.Security
            pkgs.darwin.apple_sdk.frameworks.SystemConfiguration
          ];
          
          nativeBuildInputs = [
            pkgs.pkg-config
          ];
          
          # Use sqlx-data.json for offline builds
          SQLX_OFFLINE = "true";
        };

        # Build artifacts (dependencies) only once
        cargoArtifacts = craneLib.buildDepsOnly commonArgs;

        # Server Binary
        nix-local-cache-server = craneLib.buildPackage (commonArgs // {
          inherit cargoArtifacts;
          cargoExtraArgs = "-p nix-local-cache-server";
          # Ensure we can find migrations at runtime if needed, 
          # though sqlx usually embeds them if using the macro. 
          # Our code uses sqlx::migrate!() which embeds them.
        });

        # Client Binary
        nix-local-cache-client = craneLib.buildPackage (commonArgs // {
          inherit cargoArtifacts;
          cargoExtraArgs = "-p nix-local-cache-client";
        });

        # --- Frontend Build ---
        nix-local-cache-frontend = pkgs.buildNpmPackage {
          pname = "nix-local-cache-frontend";
          version = "0.0.0";
          src = ./frontend;

          # The lockfile is generated by me in the previous step
          npmDepsHash = "sha256-mBy40ZOUX0V6FV9Q5Q/npjUbVQydxHwVq99Fl+Wk0y0=";

          installPhase = ''
            runHook preInstall
            mkdir -p $out
            cp -r dist/* $out/
            runHook postInstall
          '';
        };

      in
      {
        packages = {
          default = nix-local-cache-server;
          server = nix-local-cache-server;
          client = nix-local-cache-client;
          frontend = nix-local-cache-frontend;
        };

        # Development shell (keeps your existing devenv mostly, or replaces it)
        # I'll keep devenv.nix separate for your dev flow.
      }
    ) // {
      # Non-system-specific outputs (Modules)
      nixosModules = {
        server = import ./modules/server.nix;
        frontend = import ./modules/frontend.nix;
        default = self.nixosModules.server;
      };
    };
}
