/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIdRouteImport } from './routes/jobs/$id'
import { Route as BuildNewRouteImport } from './routes/build/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildNewRoute = BuildNewRouteImport.update({
  id: '/build/new',
  path: '/build/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/build/new': typeof BuildNewRoute
  '/jobs/$id': typeof JobsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/build/new': typeof BuildNewRoute
  '/jobs/$id': typeof JobsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/build/new': typeof BuildNewRoute
  '/jobs/$id': typeof JobsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/build/new' | '/jobs/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/build/new' | '/jobs/$id'
  id: '__root__' | '/' | '/build/new' | '/jobs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildNewRoute: typeof BuildNewRoute
  JobsIdRoute: typeof JobsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/new': {
      id: '/build/new'
      path: '/build/new'
      fullPath: '/build/new'
      preLoaderRoute: typeof BuildNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildNewRoute: BuildNewRoute,
  JobsIdRoute: JobsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
