/* This file is generated by gen_types.rs. Do not edit manually. */

export type JobStatus = "Queued" | "Running" | "Completed" | "Failed";

export type Job = { id: string, hosts: Array<string>, status: JobStatus, status_message: string | null, created_at: string, started_at: string | null, finished_at: string | null, log_path: string, flake_ref: string, timeout_seconds: bigint, results: { [key in string]?: string } | null, current_host: string | null, };

export type BuildRequest = { hosts: Array<string> | null, flake_url: string | null, flake_branch: string | null, timeout_seconds: bigint | null, };

export type PaginatedJobs = { jobs: Array<Job>, total: bigint, page: number, page_size: number, total_pages: number, };
